-- no error
CREATE TABLE MyTable (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  VALUE INT NOT NULL,
  ModifiedDate DATETIME NOT NULL CONSTRAINT DF_ModifiedDate DEFAULT GETDATE()
) WITH(DATA_COMPRESSION = ROW);

-- named constraint error on default constraint
CREATE TABLE #MyTemp1 (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  VALUE INT NOT NULL,
  ModifiedDate DATETIME NOT NULL CONSTRAINT DF_ModifiedDate DEFAULT GETDATE()
) WITH(DATA_COMPRESSION = ROW);

-- named constraint error on unique constraint
CREATE TABLE #MyTemp2 (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  VALUE INT NOT NULL CONSTRAINT UQ_Value UNIQUE,
  ModifiedDate DATETIME NOT NULL
) WITH(DATA_COMPRESSION = ROW);

-- named constraint error on check constraint
CREATE TABLE #MyTemp3 (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  VALUE INT NOT NULL CONSTRAINT CHK_Value CHECK (Value>=0),
  ModifiedDate DATETIME NOT NULL 
) WITH(DATA_COMPRESSION = ROW);

-- named constraint error on FK constraint
CREATE TABLE #MyTemp4 (
    ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    VALUE INT NOT NULL,
    ModifiedDate DATETIME NOT NULL 
    CONSTRAINT FK_ID FOREIGN KEY (ID)
      REFERENCES ID(ID)
) WITH(DATA_COMPRESSION = ROW);