CREATE TABLE MyTable (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  VALUE INT NOT NULL,
  ModifiedDate DATETIME NOT NULL CONSTRAINT DF_ModifiedDate DEFAULT GETDATE()
) WITH(DATA_COMPRESSION = ROW);