#---------------------------------#
#      general configuration      #
#---------------------------------#

# Maximum number of concurrent jobs for the project
max_jobs: 2

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  nodejs_version: "6"

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
- dotnet --info
- dotnet restore

build_script:
  - dotnet build TSQLLint.Console/TSQLLint.Console.csproj -c Release

after_build:
  - cmd: dotnet publish ./TSQLLint.Console/TSQLLint.Console.csproj -c Release -f net47 -o ../lib/net47
  - cmd: dotnet publish ./TSQLLint.Console/TSQLLint.Console.csproj -c Release -f netcoreapp2.0 -o ../lib/netcoreapp2.0
  - cmd: npm pack

test_script:
  - dotnet test ./TSQLLint.Tests/TSQLLint.Tests.csproj

after_test:
  - cmd: ./scripts/cover.cmd
  - cmd: 7z a coverage.zip %APPVEYOR_BUILD_FOLDER%\coverage

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: kKGPQj34TMA53z4dZOLj5bdvsCr1IMOqmevN2I88ssVY8BrJDroUIu0q3MLVkoOB
  artifact: /.*\.tgz/
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

artifacts:
  - path: /.*\.tgz/
  - path: coverage.zip  
