#---------------------------------#
#      general configuration      #
#---------------------------------#

max_jobs: 2

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  nodejs_version: "6"

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

# clone entire repository history if not defined
clone_depth: 5                      

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - dotnet --info

build_script:
  - cmd: IF %APPVEYOR_REPO_TAG%==false dotnet publish ./TSQLLint.Console/TSQLLint.Console.csproj -c Release -f netcoreapp2.0
  - cmd: IF %APPVEYOR_REPO_TAG%==false 7z a -ttar -so tsqllint.tar ./TSQLLint.Console/bin/Release | 7z a -si tsqllint.tgz

test_script:
  - dotnet test ./TSQLLint.Tests/TSQLLint.Tests.csproj

after_test:
  - cmd: ./scripts/cover.cmd
  - cmd: 7z a -ttar -so coverage.tar coverage | 7z a -si coverage.tgz
  - cmd: IF %APPVEYOR_REPO_TAG%==true .\scripts\publish\publish.cmd
  - cmd: IF %APPVEYOR_REPO_TAG%==true .\scripts\packageRuntimes\packageRuntimes.cmd
  - cmd: IF %APPVEYOR_REPO_TAG%==true .\scripts\tests\run-acceptance-tests.cmd
  - cmd: IF %APPVEYOR_REPO_TAG%==true npm pack

deploy:
  provider: GitHub
  auth_token:
    secure: +ldQnV1tY0iQRt0oAaumSoPCc7J2VWvS5wnnCx8blmwsnKPWzqO9uHvZ+cRKBjAP
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true

artifacts:
  - path: /**\.tgz/
