#---------------------------------#
#      general configuration      #
#---------------------------------#

# Maximum number of concurrent jobs for the project
max_jobs: 2

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  nodejs_version: "6"

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build TSQLLint.Console/TSQLLint.Console.csproj -c Release

after_build:
  - cmd: dotnet publish ./TSQLLint.Console/TSQLLint.Console.csproj -c Release -f net452 -o ../lib/net452
  - cmd: dotnet publish ./TSQLLint.Console/TSQLLint.Console.csproj -c Release -f netcoreapp2.0 -o ../lib/netcoreapp2.0
  - cmd: npm pack

test_script:
  - dotnet test ./TSQLLint.Tests/TSQLLint.Tests.csproj

after_test:
  - cmd: ./scripts/cover.cmd
- cmd: 7z a coverage.zip %APPVEYOR_BUILD_FOLDER%\coverage

artifacts:
  - path: tsqllint*.tgz
  - path: coverage.zip  
