CREATE TABLE MyTable 
	(ID INT, 
	Name nvarchar(50))
WITH (DATA_COMPRESSION = ROW);

CREATE TABLE [#SomeTempTable](
	ID INT)
WITH (DATA_COMPRESSION = PAGE);

CREATE TABLE [#SomeTempTable](
	ID INT, 
	Name nvarchar(50)
UNIQUE(ID),
CONSTRAINT CheckConstraint CHECK (Name != 'BadName'),
PRIMARY KEY CLUSTERED (ID, Name) 
WITH (DATA_COMPRESSION = PAGE, ALLOW_PAGE_LOCKS = OFF));