IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES
	WHERE ROUTINE_NAME = N'sprocName'
		AND ROUTINE_SCHEMA = N'dbo'
		AND ROUTINE_TYPE = N'PROCEDURE')
BEGIN
    SELECT 1;
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = N'dbo' 
		AND TABLE_NAME = N'tableName' 
		AND TABLE_TYPE = 'BASE TABLE')
BEGIN
	SELECT 1;
END


IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'tableName'
		AND COLUMN_NAME = 'columnName'
		AND DATA_TYPE = 'nvarchar'
		AND TABLE_SCHEMA = N'dbo') 
BEGIN
SELECT 1;
END
