SELECT FOO FROM BAR;
GO

BEGIN TRY;  
    SELECT 1;
END TRY
BEGIN CATCH;  
    SELECT 2;
END CATCH;
GO

DECLARE @KeepGoing INT = 1;
WHILE (@KeepGoing = 1)
BEGIN;
  SELECT @KeepGoing = -1;
  PRINT 'Foo';
END;
GO

IF NOT EXISTS (SELECT * FROM FOO)
BEGIN
    SELECT 1;
END
GO

CREATE TABLE t1 (
  ColumnOne int, 
  INDEX IX_ColumnOne NONCLUSTERED (ColumnOne));
GO

IF NOT EXISTS(SELECT * FROM SYS.INDEXES	WHERE OBJECT_ID = OBJECT_ID('dbo.Foo') AND [name] = 'IX_FooIndex')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX IX_FooIndex ON dbo.Foo(Name)
    WITH(DATA_COMPRESSION = PAGE, ONLINE = ON);
END
GO