SELECT * FROM MyTable;

INSERT MyTable SELECT 1, 1;

UPDATE MyTable SET x = 0;

DELETE FROM MyTable;

TRUNCATE TABLE MyTable;

CREATE TABLE MyTable (MyID INT);

DROP TABLE MyTable, dbo.AnotherTable;

ALTER TABLE MyTable ADD MyID INT NOT NULL DEFAULT(0);

ALTER TABLE MyTable DROP COLUMN MyID;
